### PR TITLE
Class prep for: 2015-11-03

### PR DESCRIPTION
**Pull request by jthopple**

### CODE REVIEW

**Comment by nmcclenn** [comment]
Hi Jeremy -
Seeing if this works to reply directly to this email. I think it might be
helpful for you to go over the structure of github.
1. How can they email you through the interface?
2. What are the different files that are being created?
3. What do the various words mean (see below)?

I want them to be able to navigate around the site easily. While much of
this will be experiential, some of the language is new to us:
repository
branch
commit
release
master

etc.

Also, once you know everyone is set up, do some initial checks for
understanding (just verbally with specific action) - ex. Send a message on
github, create a new ______, edit a blank _______.

These are all just suggestions.

Nate

ᐧ

On Mon, Nov 2, 2015 at 3:21 PM, Jeremy Hopple notifications@github.com
wrote:

> ---
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/journeys-school/6th-grade-programming/pull/3
> Commit Summary
> - Added class notes for Oct, 28
> - Class prep for Nov 3: Setup, test-driven learning, and Arithmetic
> 
> File Changes
> - _A_ .gitignore
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-0
>   (4)
> - _M_ README.md
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-1
>   (9)
> - _A_ class_notes/2015-10-28.md
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-2
>   (63)
> - _A_ class_notes/2015-11-03.md
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-3
>   (32)
> - _A_ config/config.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-4
>   (24)
> - _A_ lib/intro.ex
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-5
>   (28)
> - _A_ lib/intro/arithmetic.ex
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-6
>   (93)
> - _A_ lib/intro/labs/temp.ex
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-7
>   (3)
> - _A_ mix.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-8
>   (30)
> - _A_ test/intro/arithmetic_test.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-9
>   (4)
> - _A_ test/intro/labs/temp_test.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-10
>   (21)
> - _A_ test/intro_test.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-11
>   (4)
> - _A_ test/test_helper.exs
>   https://github.com/journeys-school/6th-grade-programming/pull/3/files#diff-12
>   (1)
> 
> Patch Links:
> - https://github.com/journeys-school/6th-grade-programming/pull/3.patch
> - https://github.com/journeys-school/6th-grade-programming/pull/3.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/journeys-school/6th-grade-programming/pull/3.

## 

_Vice President for Education and Innovation_
Teton Science Schools, 700 Coyote Canyon Rd., Jackson, WY
(307) 413-5654 (c)
(307) 734-9850 (o)

**Comment by jthopple** [comment]
@nmcclenn - great suggestions, thanks!  I have setup a few "branches" and "pull requests" in this repository. Once all of our systems are configured, we will use these example branches to begin to learn git.

**Comment by mjgrady** [comment]
:+1:

**Comment by nmcclenn** [comment]
:+1:
:100:

**Pull request merged**
